project:
  type: website
  output-dir: docs

website:
  title: "People's Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    center: |
      This project is supported by 
      [![](assets/cesta.svg){fig-alt="CESTA" width=65px}](https://cesta.stanford.edu)

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



