---
title: "People's Data"
subtitle: "a pluralist design for data in government policy and legislation"
listing:
  type: table
  contents:
    - "schema.qmd"
    - "knowledge-graph.qmd"

---
New developments in machine learning have made it possible to consider documents and collections of documents as data, thus providing important context for the inferences drawn from those sources. But even with document or collection-level context, a fundamental principle behind critical data practices remains relevant: decisions about what becomes data (and what, in turn, does not) empower some and disempower others. We add to this principle a crucial corollary: that making connections across datasets enhances the interpretation of data by adding essential context to it.
 
This case study is centered on policy manuals from California law enforcement agencies, which can help us to rethink the design of information retrieval systems by providing an ideal ground for using the affordances of AI. State legislation requires that policy manuals be shared publicly, so as to encourage “meaningful public input” on policy, yet the documents themselves are written not to enhance public understanding of law enforcement policy but to reduce the legal liability of law enforcement. To merely make these documents available and queryable via LLMs will therefore serve to perpetuate document biases. We propose, instead, to combine Natural Language Processing tools, traditional library practices of metadata creation, and a community-based knowledge graph, in order to make them more generally comprehensible and to increase their public utility.

